export const DIARY_QUESTIONS = [
  'Please tell me about yourself.',
  'Can you tell me about your house in detail?',
  'What kind of furniture do you have in your room?',
  'Which piece of furniture is your favorite Why?',
  'Can you think of any memorable events that happened in your house?',
  'Please tell me about your neighborhood.',
  'Can you tell me about a memorable event that happened in your neighborhood?',
  'Please tell me about your closest neighbors. What do you usually do with them?',
  'Please tell me about your school. Where is it? What does it look like?',
  'What kind of things do you usually do in school?',
  'Tell me about a special event that took place at school, like a graduation ceremony or a school trip.',
  'What is your major? Why did you choose it?',
  'Tell me about some of the projects that you do in school.',
  'What is the most memorable course you have taken at college?',
  'Tell me about technology you use nowadays.',
  'Tell me about the kinds of technology and equipment you use at work.',
  'What kind of technology do you use the most these days? Please tell me about your experiences using technology.',
  'How has technology changed from the past to the present?',
  'How often and when do you go to the movies? Who do you usually go with?',
  'Can you tell me about a movie theater that you often go to? Why do you often go there rather than other theaters?',
  "I'd like to tell me about one of the most memorable movies you've seen. What is the story about?",
  'How often do you go to the park? What do you usually do there?',
  'Can you describe one of the parks you often visit?',
  'Please tell me one of your memorable experiences from when you went to the park.',
  'How frequently do you go to performances and with whom do you usually go?',
  'How did you become interested in watching performances?',
  'Can you tell me about a concert venue that you like to go to?',
  'Tell me about a time when you learned how sing a song. When was it?',
  'Tell me about where you usually sing when you sing a song by yourself.',
  'Tell me about the music you sing in a group and how you practice.',
  'Have you ever sung in front of others? How did you feel?',
  'When and where do you usually listen to music? What devices do you use to listen to music?',
  'What kind of music do you like? And please tell me about your favorite singer or composer.',
  'Please tell me how your taste in music has changed from your childhood to now.',
  'How often do you exercise? When and where do you usually exercise?',
  'What kind of exercise do you like to do? How did you first become interested in that?',
  'Please tell me in detail about benefits of exercise.',
  'Do you have any interesting experiences while watching a sports game?',
  'When do you usually watch a sport game? Where do you watch it? Who do you watch it with?',
  'Please tell me about a memorable sports game you played in or watched. Why was the game so unforgettable?',
  'Can you tell me about food you like and its recipe?',
  'When and where do you usually cook? Who taught you how to cook?',
  'Which place do you like to travel to in your country? Why do you like that place?',
  'What do you usually bring when you travel overseas?',
  'When you stay at home during a vacation, what do you usually do?',
  'Can you tell me about the most memorable trip you have ever taken?',
  'How do you register for classes? Tell me about the steps.',
  'What is the most memorable class you have taken?',
  'How did you feel when you watched a play for the first time?',
  'Tell me about one of your home improvement projects.',
  'How has the transportation system changed over time?',
  'Have you ever planned a route to go somewhere? Tell me about the process.',
  'Have you changed the route to go somewhere while on the way?',
  'What do you do while watching TV?',
  'What kind of musical instruments can you play?',
  'When did you first learn how to play musical instruments?',
  'Where is the bank you go to located?',
  'How is the bank different from the past to the present?',
  'What are the responsibilities that you and your family have at home? Who is responsible for what?',
  'How has your responsibility at home changed as you grew up?',
  'Describe one of your friends.',
  'What do you think is the best way to make friends?',
  'How does friendship change over time?',
  'How did you feel when you first visited a language institute to learn a new language?',
  'Tell me about the most memorable experience you had while taking the language course.',
  'Have you ever done a project at a language institute? What happened?',
  'Have you ever thrown a party for others? Tell me about the parties you have thrown for other people.',
  'How does receiving work in your country?',
  'How do you do recycling at your house?',
  'Do you have a memorable experience regarding recycling?',
  'Tell me about what kind of things you can see at a restaurant.',
  'Tell me about a place you especially like to eat out. Tell me how to get there from home and what you normally eat there.',
  'Can you tell me about the memorable time you had at a restaurant? When was it? What kind of food do you have? Why was it so memorable?',
  'How often do you go shopping?',
  'What do you most often buy? Where do you go for shopping? Who do you go with?',
  'People sometimes go through difficult while they are shopping. How do you personally deal with those problems?',
  'Tell me about a memorable experience you had while watching a sports game.',
  'Can you tell me about your first trip abroad? Who did you go with?',
  'Tell me about your special memory when you traveled outside of your country.',
  'What do you consider most when you see a job advertisement?',
  'What are the benefits when you see a job advertisement online?',
  'How often did you exercise when you went to school?',
  'What is the best way to exercise?',
  'What do you think are the reasons to have physical education in school?',
  'When did you most recently purchase an electronic device and what did you buy?',
  'Where do you usually buy the electronic devices except for online?',
  'Is the brand important when you buy electronic devices? Why or why not?',
  'When did you recently visit a library and what did you do?',
  'How much time do you usually spend at a library when you visit?',
  'What are the benefits of reading books at a library?',
  'Have you ever changed jobs?',
  'What do you think are reasons people change their jobs?',
  'When do you people in your country visit an amusement park?',
  'Which do you prefer; going to an amusement park with friends or family? Why?',
  'If they build a new amusement park in your area, would you visit?',
  'How often do you send text messages?',
  'Who do you usually send text messages to?',
  'What are the advantages of sending text messages?',
  'When was the last time you sent or received email?',
  'Who do you usually send emails to or receive emails from?',
  'What are the advantages and disadvantages of emails compared to phone calls?',
  'When do you usually watch TV?',
  'What kind of programs do you prefer to watch and why?',
  'When did you last visit a zoo and who did you go with?',
  'Do you visit a zoo less than when you were young?',
  'What is the most important factor when you choose a zoo to visit?',
  'When do you last have video chatting?',
  'Do you think that families or friends would use more video chat and why?',
  'Which do you prefer video chatting or email? Why?',
  'What is your favorite genre of movie?',
  'Do you talk about movies after you watch them?',
  'Do you like talking about movies and why?',
  'Do you know how to ride a bicycle?',
  'How old were you when you learned how to ride a bicycle?',
  'Who taught you how to ride a bicycle?',
  'What are the benefits of riding a bicycle?',
  'Is it good for children to ride bicycles?',
  'Is it safe to ride bicycles?',
  'Are bicycles the best form of transportation?',
  'Do you think that there should be separate lanes for bicycles?',
  'Do you like to have flowers at home?',
  'Where do yu usually buy flowers?',
  'When do you buy flowers and why?',
  'What  flower colors do you like the most?',
  'Do you like smelling flowers?',
  'What do you feel when someone gives you flowers?',
  'Describe a famous person in your country.',
  'Why do people want to get fame?',
  'How can a person be famous?',
  'Which quality should a famous person have?',
  'Who were the famous persons 50 years ago and who will be famous in the next 50 years?',
  'Should they have a personal life?',
  'If you get a chance to be famous what would be your attitude?',
  'Describe a situation when you were in a traffic jam.',
  'What are the causes of traffic jams?',
  'What should we do to solve traffic problems?',
  'Do traffic jams affect the environment?',
  'What do people usually do on weekends in your country?',
  'What do you do on weekends?',
  'Do you think art is important in life, like painting and sculpture?',
  'Did you draw anything when you were at school?',
  'Are there any art galleries and museums in your hometown?',
  'Describe an animal you swa, which you find very interesting.',
  'What kind of animals people have in their home?',
  'An animal you saw which is very rare tyo see in your home town?',
  'Why people have pets in their home?',
  'Do you think people do not give enough respect to animals these days? What about 50 years ago?',
  'Earlier people used animals for their work. Now, what people use to do their work?',
  'Research is conducted on animals, is this a good idea?',
  'So many animals are extinct in these days. What do you think? Why is it happening?',
  'Describe a recent happiest event you had.',
  'What moments make other people happy?',
  'What moments are happy for elderly?',
  'Are rich people happy?',
  'Talk about a historical event that interests you.',
  'Why do you think people study history?',
  'Do you like history?',
  'How can teachers improve the way they teach history?',
  'What do you think future historians will study about us?',
  'Tell me about a building constructed recently that might be considered an historical symbol in the future.',
  'Talk about a person in your life who is very polite.',
  'Are you a polite person?',
  'Why is it important to respect each other?',
  'In what ways teachers can teach children to respect others?',
  'Do you think it should be learnt in schools?',
  'To what extend do teachers succeed in this process?',
  'Describe a room where you stayed for a long period of time.',
  'Why do you think people prefer to have small room rather than large room?',
  'What is important for good room?',
  'Do you think well organized office structure is important in company?',
  'How do you think about employees decorate their tables?',
  'Describe a party that you would like to arrange for your friends or family.',
  'What preparations would you need for this party?',
  'What kind of parties do people like to give in your country?',
  'Is there any change in this trend at present compared to the past?',
  'What reasons do you think can bring such changes?',
  "What is the relevance of international festivals or celebrations to the world's community?",
  'Talk about a foreign language (except English) that you would like to learn.',
  "Do you think it's possible to learn a country's culture without speaking the language?",
  'Do you think children learn foreign languages faster than adults?',
  'Describe a book you read or a film you saw about the future.',
  'Would you like to become a news reporter?',
  'What electronic device has significantly changed our life?',
  'Do you think computers are important in our life?',
  'Nowadays many people are concerned about the future. Do you think there are reasons to be worried about it?',
  'Talk about a job that has changed your life.',
  'Do you think changes are happening very fast nowadays?',
  'Do you think changes are a good or a bad thing?',
  'Do you think children should have changes in their lives?',
  'Talk about a science subject (such as chemistry, biology math) that you learnt in school.',
  'Should young generation be taught science subjects at school? Why?',
  'Should science subjects be taught inside or outside the classroom? Why?',
  'Why are there more men in science than women?',
  'Describe a time when you had missed something important.',
  'Talk about a comedy movie that you have watched recently and that mad you laugh.',
  'What is your opinion about humor?',
  'How important is humor in life?',
  'Do you think it is important to use humor when you teaching children in school?',
  'Do you think it is important to learn other people’s culture to be able to understand foreign comedy / humor?',
  'Do you think it is important to introduce humor in international business?',
  'Talk about an interesting advertisement that you saw.',
  'What forms of advertisements are popular?',
  'Describe a book that you are interested in.',
  'Can reading books be a hobby for everyone?',
  'What do you think about e-learning?',
  'What color do you like? Why?',
  'Do colors have some symbolic meanings in your country?',
  'Do you like / enjoy shopping?',
  'What kinds of movies do you like best?',
  'What kind of music do you enjoy most?',
  'How long do you listen to music every day?',
  'What kind of places do you like to visit?',
  'What is the first thing you will do when you arrive at a new place?',
  'What aspect of english do you find the most difficult?',
  'Does your family support your future plans?',
  'Do you want to immigrate? Why?',
  'What type of public transport do you prefer?',
  'What is the weather like in your hometown?',
  'Are there any special customs about weddings in your region?',
  'How have wedding ceremonies changed in recent years?',
  'What is the most popular sport in your country?',
  'What are the major social problems in your country?',
  'Talk about your favorite cafe or restaurant.',
  'Why do people eat junk food?',
  'What do you think about food globalization?',
  'Describe an educational trip that you had back in school and still remember.',
  'Describe a garden or a park that you like to go.',
  'Will increasing population shrink park areas?',
  'Do you think parks are necessary in urban areas?',
  'What kind of outdoor activities are popular in your country?',
  'Describe how you would spend your day off from your work or college.',
  'Do you think Asian people work harder than others?',
  'Do you prefer one long or a few short holidays? Why?',
  'Talk about an indoor game that you played in your childhood.',
  'Describe someone who can speak more than one language.',
  'Do you think it is possible to master a second language perfectly?',
  'Describe a person you know who enjoys his or her job.',
  'What kinds of occupations are popular in your country?',
  'Describe a person that you know who dresses exceptionally well.',
  'Talk about the time when someone you know surprised you.',
  'Describe a small company that you think is a successful business.',
  'Talk about an environmental law that your country should implement.',
  'What do you think about raising a pet in the dormitory?',
  'Do you think computer is helpful or not?',
  'Do you think Physical education (PE) necessary or not?',
  'Do you think Art or music class necessary or not?',
  'Do you think higher education should be available for all students?',
  'Is college education necessary to success?',
  'Some students prefer to attend universities in big cites, while others choose small towns for their higher education. Which do you prefer and why?',
  'Do you prefer living alone or living with a roommate?',
  'Do you prefer to travel alone or travel with a guide?',
  'Do you prefer reading a book or watching TV in your free time?',
  'Which genre do you like the most among novel magazine, or poem?',
  'Do we have to let children watch TV freely or not?',
  'Which is more influential to you TV or people around you?',
  'Does government invest money to arts?',
  'Save money or spend money if you have enough money?',
  'Being a leader or being a follower?',
  'Some people make decisions instantly. Others only decide after thinking about their choice for a long time. Which approach do you think is better and why?',
  'Some people try to perform several tasks at once while others prefer to concentrate on one specific task at a time. Which approach do you think is more effective and why?',
  'Some companies require their employees to wear formal business attire. Others allow casual dress. Which do you prefer and why?',
  'Some people like to eat out while others like to cook at home. Which do you think is better and why?',
  'Some people enjoy traveling around their own countries while others prefer traveling abroad. Which do you prefer and why?',
  'Some people like to communicate face-to-face while others like to communicate through e-mail. Which method do you prefer and why?',
  'Some university students are supported financially by their parents, while others support themselves with part-time jobs. Which do you think is more beneficial for students and why?',
  'Describe the best transportation in your country.',
  'Describe a place you like to go to spend time with your friends.',
  'What is your favorite place to study?',
  'If you could meet a celebrity for and hour, who would it be and why?',
  'What was the most memorable class in your school. And why was the most memorable?',
  'Describe an important holiday in your country.',
  'What is the most important achievement you have done?',
  'What is the most important characteristic of a friend?',
  'The most important quality a good leader must have?',
  'What is the most important quality of a good neighbor?',
  'What was the most significant present in your life?',
  'Which could be the best invention of the mankind? Why?',
  'Describe the season you like the most.',
  'What is your future dream job?',
  'Describe the country you would most like to visit and explain why.',
  'What is a useful skill your mother or father taught you?',
  'What was difficult experience you went through?',
  'What kind of work are you willing to do even if you never get paid for it?',
  'Of all the things you have done or not done in the past, which one has caused you the most regret?',
  'What is the worst vacation you have ever had?',
  'What are the characteristics of a good parent?',
  'Who is the most memorable teacher?',
  'What changes would you make in next 10 years?',
  'Some people spend their lives in one location, and others choose to move around from on place to another. Which do you think is better and why?',
  'Some people like to attend live performance while others prefer watching them on television. Which do you prefer and why?',
  'Some students like to study in large classes while others like to study in small ones. Which method do you think is more effective for students and why?',
  'Some people choose to spend their vacation at luxury resorts, while others prefer to backpack through different areas. Which kind of vacation do you prefer?',
  'Would you prefer to live in a traditional house or in a modern apartment building?',
  'If you could buy either a sports car or a sedan, what would you buy and why?',
  'Today, there are many people shopping online. Do you prefer shopping online rather than going shopping to the mall or market?',
  'Some people prefer to work for themselves or own a business. Others prefer to work for an employer. Would you rather be self-employed, work for someone else, or own a business?',
  'If you could go to either a place in the future or a place in the past. Which one would you choose?',
  'Which do you think it is more important to be successful in this society among physical appearance or characteristics?',
  'Some people prefer learning from books and others prefer learning from personal experience. Which one do you prefer?',
  'Do you agree or disagree with the following statement? "Celebrities like sport players and musicians have a good influence on young people."',
];
