export const DIARY_QUESTIONS = [
  'Please tell me about yourself.',
  'Can you tell me about your house in detail?',
  'What kind of furniture do you have in your room?',
  'Which piece of furniture is your favorite Why?',
  'Can you think of any memorable events that happened in your house?',
  'Please tell me about your neighborhood.',
  'Can you tell me about a memorable event that happened in your neighborhood?',
  'Please tell me about your closest neighbors. What do you usually do with them?',
  'Please tell me about your school. Where is it? What does it look like?',
  'What kind of things do you usually do in school?',
  'Tell me about a special event that took place at school, like a graduation ceremony or a school trip.',
  'What is your major? Why did you choose it?',
  'Tell me about some of the projects that you do in school.',
  'What is the most memorable course you have taken at college?',
  'Tell me about technology you use nowadays.',
  'Tell me about the kinds of technology and equipment you use at work.',
  'What kind of technology do you use the most these days? Please tell me about your experiences using technology.',
  'How has technology changed from the past to the present?',
  'How often and when do you go to the movies? Who do you usually go with?',
  'Can you tell me about a movie theater that you often go to? Why do you often go there rather than other theaters?',
  "I'd like to tell me about one of the most memorable movies you've seen. What is the story about?",
  'How often do you go to the park? What do you usually do there?',
  'Can you describe one of the parks you often visit?',
  'Please tell me one of your memorable experiences from when you went to the park.',
  'How frequently do you go to performances and with whom do you usually go?',
  'How did you become interested in watching performances?',
  'Can you tell me about a concert venue that you like to go to?',
  'Tell me about a time when you learned how sing a song. When was it?',
  'Tell me about where you usually sing when you sing a song by yourself.',
  'Tell me about the music you sing in a group and how you practice.',
  'Have you ever sung in front of others? How did you feel?',
  'When and where do you usually listen to music? What devices do you use to listen to music?',
  'What kind of music do you like? And please tell me about your favorite singer or composer.',
  'Please tell me how your taste in music has changed from your childhood to now.',
  'How often do you exercise? When and where do you usually exercise?',
  'What kind of exercise do you like to do? How did you first become interested in that?',
  'Please tell me in detail about benefits of exercise.',
  'Do you have any interesting experiences while watching a sports game?',
  'When do you usually watch a sport game? Where do you watch it? Who do you watch it with?',
  'Please tell me about a memorable sports game you played in or watched. Why was the game so unforgettable?',
  'Can you tell me about food you like and its recipe?',
  'When and where do you usually cook? Who taught you how to cook?',
  'Which place do you like to travel to in your country? Why do you like that place?',
  'What do you usually bring when you travel overseas?',
  'When you stay at home during a vacation, what do you usually do?',
  'Can you tell me about the most memorable trip you have ever taken?',
  'How do you register for classes? Tell me about the steps.',
  'What is the most memorable class you have taken?',
  'How did you feel when you watched a play for the first time?',
  'Tell me about one of your home improvement projects.',
  'How has the transportation system changed over time?',
  'Have you ever planned a route to go somewhere? Tell me about the process.',
  'Have you changed the route to go somewhere while on the way?',
  'What do you do while watching TV?',
  'What kind of musical instruments can you play?',
  'When did you first learn how to play musical instruments?',
  'Where is the bank you go to located?',
  'How is the bank different from the past to the present?',
  'What are the responsibilities that you and your family have at home? Who is responsible for what?',
  'How has your responsibility at home changed as you grew up?',
  'Describe one of your friends.',
  'What do you think is the best way to make friends?',
  'How does friendship change over time?',
  'How did you feel when you first visited a language institute to learn a new language?',
  'Tell me about the most memorable experience you had while taking the language course.',
  'Have you ever done a project at a language institute? What happened?',
  'Have you ever thrown a party for others? Tell me about the parties you have thrown for other people.',
  'How does receiving work in your country?',
  'How do you do recycling at your house?',
  'Do you have a memorable experience regarding recycling?',
  'Tell me about what kind of things you can see at a restaurant.',
  'Tell me about a place you especially like to eat out. Tell me how to get there from home and what you normally eat there.',
  'Can you tell me about the memorable time you had at a restaurant? When was it? What kind of food do you have? Why was it so memorable?',
  'How often do you go shopping?',
  'What do you most often buy? Where do you go for shopping? Who do you go with?',
  'People sometimes go through difficult while they are shopping. How do you personally deal with those problems?',
  'Tell me about a memorable experience you had while watching a sports game.',
  'Can you tell me about your first trip abroad? Who did you go with?',
  'Tell me about your special memory when you traveled outside of your country.',
  'What do you consider most when you see a job advertisement?',
  'What are the benefits when you see a job advertisement online?',
  'How often did you exercise when you went to school?',
  'What is the best way to exercise?',
  'What do you think are the reasons to have physical education in school?',
  'When did you most recently purchase an electronic device and what did you buy?',
  'Where do you usually buy the electronic devices except for online?',
  'Is the brand important when you buy electronic devices? Why or why not?',
  'When did you recently visit a library and what did you do?',
  'How much time do you usually spend at a library when you visit?',
  'What are the benefits of reading books at a library?',
  'Have you ever changed jobs?',
  'What do you think are reasons people change their jobs?',
  'When do you people in your country visit an amusement park?',
  'Which do you prefer; going to an amusement park with friends or family? Why?',
  'If they build a new amusement park in your area, would you visit?',
  'How often do you send text messages?',
  'Who do you usually send text messages to?',
  'What are the advantages of sending text messages?',
  'When was the last time you sent or received email?',
  'Who do you usually send emails to or receive emails from?',
];
